# Terraform Provider release workflow.
name: Release

# This GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created.
on:
  push:
    tags:
      - 'v*'

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@82a020f1f7f605c65dd2449b392a52c3fcfef7ef # v6.0.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - name: Print Output
        id: output
        run: pwd
      - name: Print Output2
        id: output2
        run: ls dist -al
      - uses: dcarbone/tfcloud-provider-push-action@v0.1.2 # version should be latest release
        if: ${{ success() }} # only run if previous steps succeeded
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this is created for you by Github
          TF_TOKEN: ${{ secrets.TFTOKEN }} # this assumes you've created an Action secret with this name
          TF_GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }} # this assumes you've created an Action secret with this name
          TF_REGISTRY_NAME: private
          TF_ORGANIZATION_NAME: onelittlenightmusic
          TF_NAMESPACE: onelittlenightmusic
          TF_PROVIDER_NAME: oaifile